### ISSUE TITLE
Wallets is empty

### ISSUE THREAD

**Issue by gabriella86** [beefyfinance/beefy-audits#1]
geffy audits BSC wallets is totally empty but why? Where is my token? Please help me #github``

**Comment by 1364aliyari2** [comment]
https://snapshot.org/#/playground/with-delegation?query=eyJwYXJhbXMiOnsic3ltYm9sIjoiQklGSSIsInN0cmF0ZWdpZXMiOlt7Im5hbWUiOiJlcmMyMC1iYWxhbmNlLW9mIiwicGFyYW1zIjp7ImFkZHJlc3MiOiIweDM5N2M0NEUzODAxNGU4REY2MjEyMGIwQ2JiNUVEYThCRjk3ZDU2NmEiLCJkZWNpbWFscyI6MTh9LCJuZXR3b3JrIjoiMSIsImRlc2NyaXB0aW9uIjoiZXRoZXJldW0ifSx7Im5hbWUiOiJlcmMyMC1iYWxhbmNlLW9mIiwicGFyYW1zIjp7ImFkZHJlc3MiOiIweDljNmQ4OTQyNTFFQ2RkQTM3OTBjYjNGMDk4RjhFMjUyNjAzNGM3NTMiLCJkZWNpbWFscyI6MTh9LCJuZXR3b3JrIjoiMSIsImRlc2NyaXB0aW9uIjoiZXRoZXJldW0tdW5pc3dhcC12MyJ9LHsibmFtZSI6ImVyYzIwLWJhbGFuY2Utb2YiLCJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4YzU1RTkzQzYyODc0RDgxMDBkQmQyRGZFMzA3RURjMTAzNmFkNTQzNCIsImRlY2ltYWxzIjoxOH0sIm5ldHdvcmsiOiIxMCIsImRlc2NyaXB0aW9uIjoib3B0aW1pc20tbW9vYmlmaSJ9LHsibmFtZSI6ImVyYzIwLWJhbGFuY2Utb2YiLCJwYXJhbXMiOnsiYWRkcmVzcyI6IjB4OGYzYjYzQjdCZjRjZjYzYzQxOTIwNDNERWI4MUZhMzhDQzRhMTBmYiIsImRlY2ltYWxzIjoxOH0sIm5ldHdvcmsiOiIxMCIsImRlc2NyaXB0aW9uIjoib3B0aW1pc20tbHBzIn0seyJuYW1lIjoiZXJjMjAtYmFsYW5jZS1vZiIsInBhcmFtcyI6eyJhZGRyZXNzIjoiMHgwMmJBM2IzQzFCQzNmOEYxNDMyM0I2NjQzOUYwZkIzNDE1ZGEzOTlCIiwiZGVjaW1hbHMiOjE4fSwibmV0d29yayI6IjEwIiwiZGVzY3JpcHRpb24iOiJvcHRpbWlzbS12MyJ9XX0sIm5ldHdvcmsiOiIxIiwic25hcHNob3QiOiIxOTQxOTM5NCIsImFkZHJlc3NlcyI6WyIweDNjMTNmMkI1NkFGNjE0YUM2MzgxMjY1RWNCM0I2MTliQTI2Q0M2NDEiLCIweDA0OGZlZTdjMzI3OWEyNGFmMDc5MGI2YjAwMmRlZDQyYmUwMjFkMmIiLCIweDEzOWE5MDMyYTQ2YzNhZmUzNDU2ZWI1ZjBhMzUxODNiNWYxODljYWUiXX0.
